name: Create feeds

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: master
      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: gh-pages
          path: output
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run
        env:
          TZ: "Asia/Shanghai"
        run: |
          python main.py
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: output
